services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.17-focal
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081

  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "mongodb"
    ports:
      - "8080:8080"
    env_file:
      - .env


